export declare function markdownNewLineToBr(text: string): string;
export declare function replaceAngleBrackets(text: string): string;
export declare function markdownTextToSpan(text: string): string;
export declare function markdownAsteriskToStrong(text: string): string;
export declare function markdownUnderscoreToItalics(text: string): string;
export declare function markdownBacktickToCode(text: string): string;
export declare function markdownUsernameToAbbr(text: string): string;
export declare function markdownExclamationMarkToSpoiler(text: string): string;
export declare function markdownGtToBlockquote(text: string): string;
export declare function markdownTagsToLink(text: string, currentChannelName: string): string;
export declare function parseURLToLink(text: string): string;
export declare function markdownToLink(text: string): string;
export declare function show(el: Element | Element[] | string): void;
export declare function hide(el: Element | Element[] | string): void;
export declare function isAlphanumeric(text: string): boolean;
export declare function isAlphanumericDotHyphenUnderscore(text: string): boolean;
export declare function innerHTML(el: Element | Element[] | string, html: string): void;
export declare function addClass(el: Element | Element[] | string, classArray: string | string[]): void;
export declare function removeClass(el: Element | Element[] | string, classArray: string | string[]): void;
//# sourceMappingURL=fn.d.ts.map