import * as T from './types.js';
export declare function markdownNewLineToBR(text: string, EntryObject: T.Entry): string;
export declare function replaceAngleBrackets(text: string, EntryObject: T.Entry): string;
export declare function markdownTextToSPAN(text: string, EntryObject: T.Entry): string;
export declare function markdownAsteriskToSTRONG(text: string, EntryObject: T.Entry): string;
export declare function markdownUnderscoreToITALICS(text: string, EntryObject: T.Entry): string;
export declare function markdownBacktickToCODE(text: string, EntryObject: T.Entry): string;
export declare function markdownUsernameToABBR(text: string, EntryObject: T.Entry): string;
export declare function markdownExclamationMarkToSPOILER(text: string, EntryObject: T.Entry): string;
export declare function markdownGtToBLOCKQUOTE(text: string, EntryObject: T.Entry): string;
export declare function markdownTagsToANCHOR(text: string, EntryObject: T.Entry): string;
export declare function parseURLToANCHOR(text: string, EntryObject: T.Entry): string;
export declare function markdownToANCHOR(text: string, EntryObject: T.Entry): string;
export declare function show(element: Element | Element[] | string): void;
export declare function hide(element: Element | Element[] | string): void;
export declare function isAlphanumeric(text: string): boolean;
export declare function isAlphanumericDotHyphenUnderscore(text: string): boolean;
export declare function innerHTML(el: Element | Element[] | string, html: string): void;
export declare function innerText(el: Element | Element[] | string, text: string): void;
export declare function addClass(el: Element | Element[] | string, classArray: string | string[]): void;
export declare function removeClass(el: Element | Element[] | string, classArray: string | string[]): void;
export declare function getPrefixedFlagsArray(messageContent: string): [string[], string];
export declare function areSomeValuesInArray(array: string[], values: string[]): boolean;
export declare function getEmbedVideoIDCodeFromYouTubeURL(url: string): string | boolean;
export declare function messageIDtoHexColor(id: number, lightOrDark?: string, HEXorRGBorRGBA?: string, alpha?: number): string;
export declare function toggle01(property: string | number | undefined): string | number;
export declare function isValidDate(dateString: string): boolean;
export declare function generateImageVariantsObject(url: string): Record<string, string>;
export declare function removeBlacklistWords(text: string, blacklist: string[]): string;
export declare function toggleNightMode(nightModeOn?: number | string | boolean): void;
//# sourceMappingURL=fn.d.ts.map